### ISSUE TITLE
Bones no effect on mesh.

### ISSUE THREAD

**Issue by momojohobo** [Moguri/panda3d-gltf#25] opened 2019-09-14 13:29 UTC
After converting with blend2bam the mesh is not morphed by bones even if getCurrentAnim() returns the correct animation. Exporting gltf from blender shows very erroneous animation playing in gltf-viewer. 

[floop.zip](https://github.com/Moguri/panda3d-gltf/files/3612746/floop.zip)  - play("Action")
[rebecca.zip](https://github.com/Moguri/panda3d-gltf/files/3612747/rebecca.zip)  - play("walk_forward")

**Comment by Moguri** [comment] 2019-09-15 18:49
I cannot reproduce this with v0.2, so I am closing the report. If you are still running into issues, please feel free to reopen this report and provide additional details if possible.

**Closed by Moguri** 2019-09-15 18:49 UTC
