### ISSUE TITLE
Panda3D cache is not updating when using GLTF files.

### ISSUE THREAD

**Issue by K9Kraken** [Moguri/panda3d-gltf#44] opened 2019-12-11 20:08 UTC
After having a confusing issue I found out that Panda3D will not update its model loading cache when using a GLTF file.
So if I load a GLTF file it will create the cache for it. After that if I update or delete the GLTF file Panda will still load the old file from cache.
For now I can work around this issue by using the "noCache = True" option when loading a model.

For reference on this issue:
https://discourse.panda3d.org/t/strange-issue-with-model-texture/25462/3

**Comment by Moguri** [comment] 2020-03-12 17:31
@rdb is there something special that Python File Loaders need to do to work correctly with the BAM cache? I find it surprising that the failure is that the cached version is preferred over the newer, source file as opposed to something like never using the BAM cache.

**Comment by rdb** [comment] 2020-03-12 17:40
@Moguri no, the cache should be working correctly with Python file loaders out of the box.

**Comment by Moguri** [comment] 2020-09-03 03:24
I was unable to reproduce this issue using the following steps:

* Modify the viewer to use caching and not patch the loader (i.e., rely entirely on the Python File Loader)
* Load a glTF file
* Delete the glTF file
* Try loading again

I get an error that I cannot load the glTF file (because it is missing).

Are there other steps to reproduce this? Perhaps a newer version of Panda happened to fix this? I tried this with 1.10.6.post2.

**Comment by rdb** [comment] 2020-09-03 09:32
Rather than deleting, you could try replacing the gltf file with a different one.  Panda should look at the timestamp of the file to determine whether it has changed, and I think it will refuse to load from the cache if the file has been deleted.

**Comment by Moguri** [comment] 2023-01-09 00:25
I have tried again to reproduce this by doing as @rdb suggested and tried replacing the gltf file with caching enabled. The gltf-viewer correctly showed the updated file contents despite being allowed to pull from the cache. I am closing this. If you continue to run into issues, please fell free to comment on this issue (or make a new one) with updated information on reproducing the issue.

**Closed by Moguri** 2023-01-09 00:25 UTC
Labels: bug
