### ISSUE TITLE
How can I change `skip_axis_conversion` when loading gltf files?

### ISSUE THREAD

**Issue by ragerin** [Moguri/panda3d-gltf#35] opened 2019-10-31 13:38 UTC
I wish to load gltf-files without axis conversion, like I do when I provide `--skip-axis-conversion` on the commandline.

Is this possible? It eludes me how this can be achieved.

Thanks in advance!

**Comment by el-dee** [comment] 2019-10-31 13:49
If you are using the loader, you can customize the settings like this :

    GltfLoader.global_settings = GltfSettings(skip_axis_conversion=True)

before loading your model.

**Comment by ragerin** [comment] 2019-11-11 14:30
I'm using the loader, without the patch_loader - specifying the setting you provided didn't change the outcome, like it does when using the `gltf2bam`-converter, with `--skip-axis-conversion`.

Can you give an example of where to put `GltfLoader.global_settings = GltfSettings(skip_axis_conversion=True)`? I put it in the file-scope, just before declaring my ShowBase-class, with no effect.

**Comment by Moguri** [comment] 2019-11-11 21:43
Adding that line anytime after importing GltfLoader and before loading the file should work. I run a similar hack to `viewer.py` locally. I can double-check what I do an post an example when I get home.

**Comment by Moguri** [comment] 2019-11-15 04:55
I commented out the `gltf.patch_loader()` call in viewer.py and replaced it with `gltf.GltfLoader.global_settings = gltf.GltfSettings(skip_axis_conversion=True)`, and that worked. I also tried moving the line outside of the `App` class declaration, and that worked too.

**Comment by ragerin** [comment] 2019-11-15 12:29
Thanks for your answers.

@Moguri so you have to patch `viewer.py` locally in order to override the global_settings, is that correct?

**Comment by K9Kraken** [comment] 2019-11-18 02:10
I'm a little confused?
In Blender gltf export I unchecked the "+Y Up" option to keep Z as up. When loading in to Panda3D the script rotates the model so Y is up. I then have to end up doing the extra step to use gltf2bam with the "--skip-axis-conversion" option.

Is this done on purpose by design?
If it is then what is the purpose of rotating the model so it does not match what is exported?
Is my only option of simplifying the workflow is editing the script as stated above?

**Comment by el-dee** [comment] 2019-11-18 07:45
Panda3d-gltf assumes that the model is in "+Y up" coordinate system, unless there is **BP_zup** extension specified in the gltf file or you specify skip-axis-conversion on the command line or in the option.

It seems that the current glTF exporter of Blender does not add thee BP_zup extension in the exported file (which seems logical as there is no mention of that extension in the glTF norm), hence panda3d-gltf assumes the model is in "+Y up" cs and convert it as Panda is by default "+Z up".

**Comment by rdb** [comment] 2019-11-18 07:49
Yes, I want to stress that if you uncheck "+Y" in the Blender exporter, Blender creates an *invalid* glTF file, because a valid glTF file is by definition using the Y-up coordinate system.  Worse yet, Blender does not even change anything in the file that indicates that it was exported in Z-up.

Do not uncheck "+Y" in the Blender exporter unless you are very specifically also going out of your way to also disable axis conversion in the importer (but in this case you should probably be using blend2bam), because it creates an unportable glTF file that no conforming loader will be able to load correctly.

**Comment by ragerin** [comment] 2019-11-18 11:28
@rdb that is indeed a bit concerning.

In regards to using `panda3d-gltf`, I've failed to override the `skip_axis_conversion` in the global settings during runtime (before defining my ShowBase application).

It's definitely a workaround to use the `blend2bam` or `gltf2bam`  with `--skip-axis-conversion`, as @K9Kraken also stated, but I'd have expected overriding the setting in the global settings would have sufficed. I just haven't been able to make this work.

**Comment by rdb** [comment] 2019-11-18 11:36
Given that #34 is now fixed, is there a particular reason you wish to avoid the axis conversion?  Have you found a model that does not produce the correct result after a round-trip conversion?

**Comment by K9Kraken** [comment] 2019-11-18 15:23
Thanks for the explanation.
I have tried leaving the +Y checked and when loading in to Panda3D the model is upside down with -Z as up.
I did install the latest doing: "pip install git+https://github.com/Moguri/panda3d-gltf.git"

I did not know that Blend2Bam existed thanks, but a simple workflow that this script provides would be nice.

**Comment by Moguri** [comment] 2020-10-16 03:04
I have gone and double-checked that disabling axis conversion via the global settings does work as intended. If it is not working, please post some sample code. In the mean time, I am going to close this issue. We can re-open it if it's still not working for you.

**Closed by Moguri** 2020-10-16 03:04 UTC
